apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: argo-cd-cert
spec:
  secretName: argocd-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: ClusterIssuer
    namespace: cert-manager
  commonName: cd.apps.argoproj.io
  dnsNames:
  - cd.apps.argoproj.io
  acme:
    config:
    - http01:
        ingress: argo-ui
      domains:
      - cd.apps.argoproj.io
