apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
    targetVersion: a52c24dfa5e9b8dbdc5ff5092a6fef864792cfeb
  project: default
  source:
    path: stable/cert-manager
    repoURL: https://github.com/helm/charts
    targetRevision: HEAD
  syncPolicy:
    automated: {}
