apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kind-operator
spec:
  destination:
    namespace: argoci
    server: https://kubernetes.default.svc
  project: default
  source:
    path: config/default
    repoURL: https://github.com/alexmt/kind-operator
    targetRevision: HEAD
