apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: workflow
spec:
  template:
    serviceAccountName: argo-events-sa
  dependencies:
    - name: test-dep
      eventSourceName: calendar
      eventName: example-with-interval
  triggers:
    - template:
        name: argo-workflow-trigger
        log: {}