resources:
- base/argo-workflows.yaml
- base/argocd.yaml
- base/cert-manager.yaml
- base/nginx-ingress.yaml
- base/jenkins.yaml
- base/prometheus-operator.yaml
- base/istio-operator.yaml
- base/istio-controlplane.yaml
- base/istio-addons.yaml
