apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/argo-cd-issuer.yaml
- base/argo-cd-certificate.yaml
- base/http01-ingress.yaml
- base/argo-cd-ui-ingress.yaml

bases:
- github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=release-0.12

patchesStrategicMerge:
- overlays/production/argo-cd-cm.yaml
- overlays/production/argocd-server-service.yaml
- overlays/production/argocd-server-deploy.yaml

namespace: argocd
