apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/argo-cd-issuer.yaml
- base/argo-cd-certificate.yaml
- base/http01-ingress.yaml
- base/argo-cd-ui-ingress.yaml
- base/jenkins-ingress.yaml
- github.com/argoproj/argo-cd//manifests/ha/cluster-install?ref=release-1.4
- github.com/argoproj-labs/argocd-notifications//manifests/base?ref=release-0.3


patchesStrategicMerge:
- overlays/production/argo-cd-cm.yaml
- overlays/production/argocd-server-service.yaml
- overlays/production/argocd-server-deploy.yaml
- overlays/production/argocd-repo-server-deploy.yaml
- overlays/production/argocd-notifications-cm.yaml

namespace: argocd

images:
- name: argoproj/argocd
  newName: docker.pkg.github.com/argoproj/argo-cd/argocd
  newTag: 1.5.0-0e9e6286
- name: argoprojlabs/argocd-notifications
  newName: docker.pkg.github.com/argoproj-labs/argocd-notifications/argocd-notifications
  newTag: 0.5.0-6c75688f
