apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/argo-cd-issuer.yaml
- base/argo-cd-certificate.yaml
- base/http01-ingress.yaml
- base/argo-cd-ui-ingress.yaml
- base/jenkins-ingress.yaml
- base/argo-cd-notifications-bot-ingress.yaml
- base/argo-cd-notifications-bot-certificate.yaml
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install
- https://github.com/argoproj-labs/argocd-notifications/manifests/bot


patchesStrategicMerge:
- overlays/production/argo-cd-cm.yaml
- overlays/production/argocd-server-service.yaml
- overlays/production/argocd-repo-server-deploy.yaml
- overlays/production/argocd-notifications-cm.yaml
- overlays/production/argocd-notifications-bot-service.yaml

patchesJson6902:
- path: overlays/production/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocd

images:
- name: argoproj/argocd
  newName: docker.pkg.github.com/argoproj/argo-cd/argocd
  newTag: 1.8.0-6ddd98c4
- name: argoprojlabs/argocd-notifications
  newName: docker.pkg.github.com/argoproj-labs/argocd-notifications/argocd-notifications
  newTag: 0.7.0-582ae886
