resources:
- base/argo-cd-issuer.yaml
- base/argo-cd-certificate.yaml
- base/http01-ingress.yaml

bases:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=v0.11.0

patchesStrategicMerge:
- overlays/production/argo-cd-cm.yaml
namespace: argocd
