apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/argo-ns.yaml
  - https://github.com/argoproj/argo/manifests/namespace-install
  - resources/argo-server-ingress.yaml
  - resources/canary-cronworkflow.yaml
  - resources/coinflip-workflowtemplate.yaml
  - resources/coinflip-cronworkflow.yaml

patchesStrategicMerge:
  - overlays/workflow-controller-configmap.yaml
  - overlays/argo-server-role.yaml

patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: argo-server
    path: ./overlays/argo-server-deployment.yaml

namespace: argo
