apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/argo-ns.yaml
- https://github.com/argoproj/argo/manifests/namespace-install
- resources/argo-server-ingress.yaml
- resources/argo-workflows-certificate.yaml
- resources/argo-workflows-issuer.yaml
- resources/canary-cronworkflow.yaml
- resources/coinflip-workflowtemplate.yaml
- resources/coinflip-cronworkflow.yaml
- resources/argo-sa.yaml
- resources/workflow-role.yaml
- resources/argo-rolebinding.yaml

patchesStrategicMerge:
- overlays/workflow-controller-configmap.yaml
- overlays/argo-server-role.yaml
- overlays/argo-server-sa.yaml

patchesJson6902:
- path: ./overlays/argo-server-deployment.yaml
  target:
    group: apps
    kind: Deployment
    name: argo-server
    version: v1

namespace: argo
images:
- name: argoproj/argocli
  newTag: ui-v3
