apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/argo-ns.yaml
  - https://github.com/argoproj/argo/manifests/namespace-install
  - resources/argo-server-ingress.yaml

patchesStrategicMerge:
  - resources/workflow-controller-configmap.yaml
  - resources/argo-server-role.yaml

namespace: argo
