apiVersion: v1
data:
  # https://github.com/settings/applications/1416526
  sso: |
    issuer: https://api.github.com
    clientId:
      name: argo-server-sso
      key: clientID
    clientSecret:
      name: argo-server-sso
      key: clientSecret
    redirectUrl: https://argo-server.apps.argoproj.io/oauth2/callback
    scopes:
    - groups
  containerRuntimeExecutor: pns
  workflowDefaults: |
    spec:
      ttlStrategy:
        secondsAfterCompletion: 600
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
