- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --secure=false
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --auth-mode=sso
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --auth-mode=client
- op: add
  path: /spec/template/spec/containers/0/args/-
  value:
    --x-frame-options=SAMEORIGIN