apiVersion: v1
data:
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: fb563b3a8dd7ea52f683
        clientSecret: $dex.github.clientSecret
  url: https://cd.apps.argoproj.io
kind: ConfigMap
metadata:
  name: argocd-cm
