apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        command:
        - argocd-server
        - --insecure
        - --staticassets
        - /shared/app
        - --sentinel
        - argocd-redis-ha-announce-0:26379
        - --sentinel
        - argocd-redis-ha-announce-1:26379
        - --sentinel
        - argocd-redis-ha-announce-2:26379
        - --sentinelmaster
        - argocd
      volumes:
      - name: custom-tools
        emptyDir: {}
      initContainers:
      - name: download-tools
        image: alexmt/argocd-flux:latest
        command: [sh, -c]
        args:
        - cp /usr/local/bin/argocd-flux-plugin /custom-tools/argocd-flux-plugin
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
