apiVersion: v1
data:
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: fb563b3a8dd7ea52f683
        clientSecret: 1fcbf1f3fee74ef7dc3942be63f2a5226c62e649
  url: https://argo-cd-demo.argoproj.io
kind: ConfigMap
metadata:
  name: argocd-cm
