apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
data:
  context: |
    argocdUrl: https://cd.apps.argoproj.io

  trigger.sync-operation-change: |
    - when: app.status.operationState.phase in ['Succeeded']
      send: [app-sync-succeeded, github-commit-status]
    - when: app.status.operationState.phase in ['Error', 'Failed']
      send: [app-sync-failed, github-commit-status]
    - when: app.status.operationState.phase in ['Running']
      send: [app-sync-running, github-commit-status]

  trigger.health-change: |
   - when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
     send: [app-sync-succeeded]
     oncePer: app.status.sync.revision
   - when: app.status.health.status == 'Degraded'
     send: [app-health-degraded]

  templates.github-commit-status: |
    webhook:
      github:
        method: POST
        path: /repos/{{call .repo.FullNameByRepoURL .app.spec.source.repoURL}}/statuses/{{.app.status.operationState.operation.sync.revision}}
        body: |
          {
            {{if eq .app.status.operationState.phase "Running"}} "state": "pending"{{end}}
            {{if eq .app.status.operationState.phase "Succeeded"}} "state": "success"{{end}}
            {{if eq .app.status.operationState.phase "Error"}} "state": "error"{{end}}
            {{if eq .app.status.operationState.phase "Failed"}} "state": "error"{{end}},
            "description": "ArgoCD",
            "target_url": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
            "context": "continuous-delivery/{{.app.metadata.name}}"
          }

  service.slack: |
    token: $slack-token
    signingSecret: $slack-signing-secret
  
  service.webhook.github: |
    url: https://api.github.com
    headers: #optional headers
    - name: Authorization
      value: token $github-token
