apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: argo-ci-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: amatyushentsev@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    http01: {}
