apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: amatyushentsev@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}
